require 'uri'
require 'net/http'
require 'zlib'

class Sitemap
  ## caching mit etag, last_modified, expires_in
  
  def initialize
    raw_config = File.read(RAILS_ROOT + "/config/sitemap_config.yml")
    @SITEMAP_CONFIG = YAML.load(raw_config)[RAILS_ENV].symbolize_keys
  end
  
  def build
    xml_str = ""
    xml = Builder::XmlMarkup.new(:target => xml_str, :indent => 1)
    
    xml.instruct!
    xml.instruct! "xml-stylesheet", :type => "text/xsl", :href => "/sitemap.xsl"
    xml.comment!("Generated by XML Sitemap Generator for Rails http://github.com/fsmanuel/xml_sitemap_generator/")
    # TODO add sitemap-generator-url= sitemap-generator-version= generated-on=

    xml.urlset  "xmlns:xsi" => "http://www.w3.org/2001/XMLSchema-instance",
                "xsi:schemaLocation" => "http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd",
                "xmlns" => "http://www.sitemaps.org/schemas/sitemap/0.9" do
      xml.url do
        xml.loc         @SITEMAP_CONFIG[:domain]
        xml.lastmod     w3c_date(Time.now)
        xml.changefreq  "always"
        xml.priority    1.0
      end

      @SITEMAP_CONFIG[:models].each do |sitemap_model|
        urls = sitemap_model.camelize.constantize.find_for_sitemap
        
        urls.each do |url|
          xml.url do
            xml.loc         "#{@SITEMAP_CONFIG[:domain]}/#{sitemap_model}s/#{url.to_param}"
            xml.lastmod     w3c_date(url.updated_at)
            xml.changefreq  "weekly"
            xml.priority    0.8
          end
        end
      end
    end
    
    @xml = xml_str
  end
  
  def save
    File.open(RAILS_ROOT + "/public/sitemap.xml", 'w+') do |f|
      f.write @xml
      f.close
    end
    
    File.open(RAILS_ROOT + "/public/sitemap.xml.gz", 'w+') do |f|
      gz = Zlib::GzipWriter.new(f)
      gz.write @xml
      gz.close
    end
  end

  # Notify Google of the new sitemap index file
  def update_google
    sitemap_uri = @SITEMAP_CONFIG[:domain] + '/sitemap.xml.gz'
    escaped_sitemap_uri = URI.escape(sitemap_uri)
    Net::HTTP.get('www.google.com', '/webmasters/tools/ping?sitemap=' + escaped_sitemap_uri)
  end
  
  def w3c_date(date)
    date.utc.strftime("%Y-%m-%dT%H:%M:%S+00:00")
  end
  
end